version: '3.9'
services:
  backend:
    build: ./backend
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - GOOGLE_FCM_PROJECT_ID=${GOOGLE_FCM_PROJECT_ID}
    ports:
      - "3001:3001"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3001/ready"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

