include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
  errors:
    missing_required_param: error
    missing_return: error
    dead_code: warning
    unused_local_variable: warning

linter:
  rules:
    avoid_print: true
    prefer_final_locals: true
    always_declare_return_types: true
    use_build_context_synchronously: true
